name: favorite_places_new
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_riverpod: ^2.5.1
  geocoding: ^3.0.0
  google_fonts: ^6.2.1
  image_input: ^0.0.5
  location: ^7.0.1
  path: ^1.9.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
